// @ts-nocheck
/* eslint-disable */
// --------------------------------------------------
// This file is auto-generated by Tuyau. Do not edit manually !
// --------------------------------------------------

import type { MakeTuyauRequest, MakeTuyauResponse } from '@tuyau/utils/types'
import type { InferInput } from '@vinejs/vine/types'

type ApiAuthLoginPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/auth/controllers/login_controller.ts').default['validator']>>
  response: MakeTuyauResponse<import('../app/auth/controllers/login_controller.ts').default['handle'], true, import('../app/auth/controllers/login_controller.ts').default['validationExceptionResponse']>
}
type ApiAuthIdRedirectGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/auth/controllers/external_provider_login_controller.ts').default['redirect'], false>
}
type ApiAuthRegisterPost = {
  request: MakeTuyauRequest<InferInput<typeof import('../app/auth/controllers/register_controller.ts').default['validator']>>
  response: MakeTuyauResponse<import('../app/auth/controllers/register_controller.ts').default['handle'], true>
}
type ApiMeGetHead = {
  request: unknown
  response: MakeTuyauResponse<import('../app/me/controllers/me_controller.ts').default['index'], false>
}
export interface ApiDefinition {
  'api': {
    'auth': {
      'login': {
        '$url': {
        };
        '$post': ApiAuthLoginPost;
      };
      ':provider': {
        'redirect': {
          '$url': {
          };
          '$get': ApiAuthIdRedirectGetHead;
          '$head': ApiAuthIdRedirectGetHead;
        };
      };
      'register': {
        '$url': {
        };
        '$post': ApiAuthRegisterPost;
      };
    };
    'me': {
      '$url': {
      };
      '$get': ApiMeGetHead;
      '$head': ApiMeGetHead;
    };
  };
}
const routes = [
] as const;
export const api = {
  routes,
  definition: {} as ApiDefinition
}
